language: java
jdk:
  - oraclejdk8
after_success:
  - wget https://raw.githubusercontent.com/brainsynder-Dev/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/brainsynder-Dev/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
