language: java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://discord.pluginwiki.us/travis.php
    on_success: always
    on_failure: always
    on_start: always

script:
 - bash fetch_dependencies.sh
 - mvn package

deploy:
  provider: releases
  api_key:
    secure: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxkzDR07jj98BRAkndbkJ\nQyt2+h/XEoRC33/UUiyTfTqFUdya5bJALGwHKF6l42I1taZU7Ukec0UmS6pCY19m\nDxys3kaeHFLD6x+fk3rjPcOV0YguY9kmE9IGrIDApQfhbytn0wK/57/HW+yyz0bU\nQGXToEzcw/kFtP+X0TuCbXuNJXfxZ0cVx1YWE/ogJxGaIydJl+sMTxWw8qqQ6Crx\nvyFBLyMqxMocsaSGE3yx+xt+qLmzZbdXyI4XfcZc26hQ6S5y08+g3poQWYY68X9v\n7M7m+Jl/jOWOiz+mLR2zYs1OpONqI/8twLkIYARRGo+tAbOx7SO2vlE8kNQcEk95\nQJMzdwOKvTyNnsyt/z4UFttzC/W80TQh4wzRk1ZpS7W9TMX1cyvV5AYh0yN1hTAz\nweHvSPJXksQxb6AT9DFXlYwlLFs7ycajhPm8UMoz7iLguyZHUM5Tz3i1yYrO787+\nEmPsi++ZNbMcDFrJ4fi4lCSfa/l9cCSQTBwUaJ+fH1k377Fd/jiGkWOyOumQcoRX\naxqPGsgMk8h9eejmB9X4rVWTi1fjIDde9cYdEWa95IXEm624x6iFL09MrzSD2GD8\nyf0ryaQm3ridDnHNZxHpGVJI1tLgbvxAEWKyf8cC8meP5Md8uutxCFIzeMRc/Wfv\nVWyWJE3dFmouc3IeP31SDLkCAwEAAQ=="
  file: "target/SimplePets.jar"
  skip_cleanup: true
  on:
    tags: true
